name: Setup build environment
on: push
jobs:
  setup-build-env:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        ANDROID_ABI: [armeabi-v7a,arm64-v8a,x86,x86_64]
    steps:
      # [BEGIN] Act compatibility
      # https://github.com/nektos/act does not have the Android NDK installed
      - name: Get Android NDK variable
        id: get-android-ndk
        run: if [ "${ANDROID_NDK}" = "" ]; then export ANDROID_NDK="~/android-ndk-r23b";fi;echo "::set-output name=value::${ANDROID_NDK}"
      - if: ${{ steps.get-android-ndk.outputs.value == '~/android-ndk-r23b' }}
        name: Use Android NDK cache
        id: cache-android-ndk
        uses: actions/cache@v3
        with:
          path: ~/android-ndk-r23b
          key: cache-android-ndk-r23b
      - if: ${{ steps.get-android-ndk.outputs.value == '~/android-ndk-r23b' && steps.cache-android-ndk.outputs.cache-hit != 'true' }}
        name: Install Android NDK
        run: wget "https://dl.google.com/android/repository/android-ndk-r23b-linux.zip" && unzip "android-ndk-r23b-linux.zip" -d ~
      # https://github.com/nektos/act does not have cmake installed
      - name: Get CMake if not present
        run: cmake -v || (sudo apt-get update && sudo apt-get install -y -q cmake)
      # [END] Act compatibility
      - name: Check out AprilTag
        uses: actions/checkout@v3
        with:
          repository: AprilRobotics/apriltag
          ref: d6b7d1c28e7310b925dcfc4b0b67622608b489d3
          lfs: true
          submodules: recursive
          path: ./apriltag
      - name: Configure AprilTag
        run: cmake -B ./apriltag/build -DCMAKE_SYSTEM_NAME=Android -DCMAKE_TOOLCHAIN_FILE="${{ steps.get-android-ndk.outputs.value }}/build/cmake/android.toolchain.cmake" -DANDROID_ABI="${{ matrix.ANDROID_ABI }}" -DCMAKE_BUILD_TYPE=Release ./apriltag
      - name: Build AprilTag
        run: cmake --build ./apriltag/build --config Release --target apriltag
      - name: Store AprilTag's library
        uses: actions/upload-artifact@v3
        with:
          name: libapriltag-android-${{ matrix.ANDROID_ABI }}
          path: ./apriltag/build/libapriltag.so